/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Business.UserBusiness;
import Logic.AdjacenceList;
import Logic.LinkedQueue;
import Utility.Routh;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdom.JDOMException;

/**
 *
 * @author vanes
 */
public class JFFriendships extends javax.swing.JFrame {
    String us;
    LinkedQueue queueRequest;
    LinkedQueue queueDate;
    LinkedQueue queue;
    ArrayList<String> friends = new ArrayList<>();
    ArrayList<String> friendFriend = new ArrayList<>();
    int x=0;
    AdjacenceList graph;
    int c =0;
    /**
     * Creates new form JFFriends
     */
    public JFFriendships(String us) throws JDOMException, IOException {
        initComponents();
        this.us = us;
        this.jLFriends.setVisible(false);
        this.jLUser.setVisible(false);
        this.jLMessage.setVisible(false);
        this.jbSend.setVisible(false);
        this.jPTe.setVisible(false);
        this.jLUser3.setVisible(false);
        this.jLDate.setVisible(false);
        this.jLMessage3.setVisible(false);
        getFriends();
        getRequest();
        showRequest();
        getSuggestion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLUser3 = new javax.swing.JLabel();
        jLDate = new javax.swing.JLabel();
        jLFriends3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLMessage3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLUser2 = new javax.swing.JLabel();
        jLFriends2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLMessage2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAFriends = new javax.swing.JTextArea();
        jLMessage4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFUser = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPTe = new javax.swing.JPanel();
        jbSend = new javax.swing.JButton();
        jLUser = new javax.swing.JLabel();
        jLFriends = new javax.swing.JLabel();
        jLMessage = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(23, 172, 170));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLUser3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLUser3.setText("User");

        jLDate.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLDate.setText("Date");

        jLFriends3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLFriends3.setText("Friends");

        jButton4.setBackground(new java.awt.Color(23, 172, 170));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Accept");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLMessage3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLMessage3.setForeground(new java.awt.Color(204, 0, 0));
        jLMessage3.setText("message");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLUser3)
                        .addGap(53, 53, 53)
                        .addComponent(jLDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLFriends3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLMessage3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLUser3)
                    .addComponent(jLDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLMessage3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jLFriends3))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Requests", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLUser2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLUser2.setText("User ");

        jLFriends2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLFriends2.setText("Friends");

        jButton3.setBackground(new java.awt.Color(23, 172, 170));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Send");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLMessage2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLMessage2.setForeground(new java.awt.Color(204, 0, 0));
        jLMessage2.setText("Message");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLFriends2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLUser2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLMessage2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLUser2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLMessage2)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFriends2)
                    .addComponent(jButton3))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Suggestion", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTAFriends.setColumns(20);
        jTAFriends.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jTAFriends.setRows(5);
        jTAFriends.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTAFriends);

        jLMessage4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLMessage4.setForeground(new java.awt.Color(204, 0, 0));
        jLMessage4.setText("Message");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLMessage4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLMessage4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Friends", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel2.setText("User name:");

        jButton2.setBackground(new java.awt.Color(23, 172, 170));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Search");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPTe.setBackground(new java.awt.Color(255, 255, 255));
        jPTe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbSend.setBackground(new java.awt.Color(23, 172, 170));
        jbSend.setForeground(new java.awt.Color(255, 255, 255));
        jbSend.setText("Send");
        jbSend.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSendActionPerformed(evt);
            }
        });

        jLUser.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLUser.setText("User");

        jLFriends.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLFriends.setText("Friends");

        jLMessage.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLMessage.setForeground(new java.awt.Color(204, 0, 0));
        jLMessage.setText("Message");

        javax.swing.GroupLayout jPTeLayout = new javax.swing.GroupLayout(jPTe);
        jPTe.setLayout(jPTeLayout);
        jPTeLayout.setHorizontalGroup(
            jPTeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTeLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLFriends)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jbSend, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPTeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLUser)
                .addGap(18, 18, 18)
                .addComponent(jLMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPTeLayout.setVerticalGroup(
            jPTeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTeLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPTeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTeLayout.createSequentialGroup()
                        .addComponent(jLUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTeLayout.createSequentialGroup()
                        .addComponent(jLMessage)
                        .addGap(2, 2, 2)))
                .addGroup(jPTeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTeLayout.createSequentialGroup()
                        .addComponent(jbSend)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTeLayout.createSequentialGroup()
                        .addComponent(jLFriends)
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTFUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(24, 24, 24))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPTe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jPTe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        jTabbedPane1.addTab("Search", jPanel5);

        jButton1.setText("Go back");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FRIENDSHIPS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jButton1)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void getSuggestion() throws JDOMException, IOException{
        UserBusiness userBusiness = new UserBusiness(Routh.routhUssers);
        graph = userBusiness.fillGraph();
        friendFriend = (userBusiness.getFriends(friends.get(c)));
        if(graph.verify(this.us)){
            if (!(graph.existEdge(this.us, friendFriend.get(c)))) {
                this.jLMessage2.setVisible(false);
                 this.jLUser2.setVisible(true);
                this.jLUser2.setText(friendFriend.get(c+1));
            }else{
                this.jLMessage2.setVisible(true);
                this.jLUser2.setVisible(false);
                this.jLMessage2.setText("We don't have suggestions for you");
            }
        }else{
            this.jLMessage2.setVisible(true);
                this.jLUser2.setVisible(false);
                this.jLFriends2.setVisible(false);
                this.jLMessage2.setText("We don't have suggestions for you");
        }
    }
    private void getFriends() throws JDOMException, IOException{
        this.jTAFriends.setText(" ");
        UserBusiness userBusiness = new UserBusiness(Routh.routhUssers);
        friends = userBusiness.getFriends(this.us);
        if(!friends.isEmpty()){
            this.jLMessage4.setVisible(false);
            for (int i = 0; i < friends.size(); i++) {
                this.jTAFriends.append("Friend: "+friends.get(i)+"\n");
            }
        }else{
            this.jLMessage4.setVisible(true);
            this.jLMessage4.setText("Don't have friends");
        }
        
    }
    private void getRequest() throws JDOMException, IOException {
        UserBusiness userBusiness = new UserBusiness(Routh.routhUssers);
        this.queue = userBusiness.getRequest(this.us);
        this.queueDate = new LinkedQueue();
        this.queueRequest = new LinkedQueue();

        if (!this.queue.isEmpty()) {

            String que = (String) queue.delete();
            String[] date = que.split("/");

            for (int i = 0; i < date.length - 1; i++) {

                this.queueDate.insert(date[i]);
                this.queueRequest.insert(date[i + 1]);
                
            }
            for (int i = 0; i < this.queueRequest.getSize(); i++) {
                String f =(String) this.queueRequest.delete();
                String d =(String) this.queueDate.delete();
                for (int j = 0; j < friends.size(); j++) {
                    if(f.equals(friends.get(i))){
                       x++; 
                    }
                }
                if (x==0) {
                    this.queueRequest.insert(f);
                    this.queueDate.insert(d);
                }
            }  
        }

    }

    private void showRequest() throws JDOMException{
        if(!this.queueDate.isEmpty()){
            this.jLMessage3.setVisible(false);
            this.jLUser3.setVisible(true);
            this.jLDate.setVisible(true);
            this.jLUser3.setText((String) this.queueRequest.delete());
            this.jLDate.setText((String) this.queueDate.delete());
        }else{
            this.jLUser3.setVisible(false);
            this.jLDate.setVisible(false);
            this.jLMessage3.setVisible(true);
            this.jLMessage3.setText("Don't have request");
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.jLFriends.setVisible(false);
        this.jLUser.setVisible(false);
        this.jLMessage.setVisible(false);
        this.jbSend.setVisible(false);
        this.jPTe.setVisible(false);
        
        try {
            UserBusiness userBusiness = new UserBusiness(Routh.routhUssers);
            if(userBusiness.searchUser(this.jTFUser.getText())){
                this.jLFriends.setVisible(true);
                this.jLUser.setVisible(true);
                this.jbSend.setVisible(true);
                this.jLUser.setText(this.jTFUser.getText());
                this.jPTe.setVisible(true);
            }else{
                this.jLUser.setText(" ");
                this.jLMessage.setVisible(true);
                this.jLMessage.setText("Don't found");
                this.jPTe.setVisible(true);
            }
            
        } catch (JDOMException ex) {
            Logger.getLogger(JFFriendships.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JFFriendships.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSendActionPerformed
         try {
            DateFormat dateFormat = new SimpleDateFormat("EEE, MMM d, yyyy '@' HH:mm:ss/");
            String date = dateFormat.format(Calendar.getInstance().getTime());
            UserBusiness userBusiness = new UserBusiness(Routh.routhUssers);
            userBusiness.addRequest(this.us, this.jTFUser.getText(), date);
            
        } catch (JDOMException ex) {
            Logger.getLogger(JFFriendships.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JFFriendships.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jbSendActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            JFPrincipal jFPrincipal = new JFPrincipal(this.us);
            jFPrincipal.setVisible(true);
            jFPrincipal.setLocationRelativeTo(null);	
            this.setVisible(false);
        } catch (JDOMException ex) {
            Logger.getLogger(JFFriendships.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JFFriendships.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(JFFriendships.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            showRequest();
            UserBusiness userBusiness = new UserBusiness(Routh.routhUssers);
            if(this.jLUser3.getText().equals(" ")){
                getFriends();
            }else{
                userBusiness.acceptRequest(this.us, this.jLUser3.getText());
                getFriends();
            }
            
        } catch (JDOMException ex) {
            Logger.getLogger(JFFriendships.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JFFriendships.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if(this.jLMessage2.getText().equals("We don't have suggestions for you")){
                getSuggestion();
            }else{
            DateFormat dateFormat = new SimpleDateFormat("EEE, MMM d, yyyy '@' HH:mm:ss/");
            String date = dateFormat.format(Calendar.getInstance().getTime());
            UserBusiness userBusiness = new UserBusiness(Routh.routhUssers);
            userBusiness.addRequest(this.us, this.jLUser2.getText(), date);
            c++;
            getSuggestion();
            }
            
        } catch (JDOMException ex) {
            Logger.getLogger(JFFriendships.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JFFriendships.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLDate;
    private javax.swing.JLabel jLFriends;
    private javax.swing.JLabel jLFriends2;
    private javax.swing.JLabel jLFriends3;
    private javax.swing.JLabel jLMessage;
    private javax.swing.JLabel jLMessage2;
    private javax.swing.JLabel jLMessage3;
    private javax.swing.JLabel jLMessage4;
    private javax.swing.JLabel jLUser;
    private javax.swing.JLabel jLUser2;
    private javax.swing.JLabel jLUser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPTe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAFriends;
    private javax.swing.JTextField jTFUser;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbSend;
    // End of variables declaration//GEN-END:variables
}
