/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logic.CircularDoubleLinkedList;

/**
 *
 * @author vanes
 */
public class JFThoughts extends javax.swing.JFrame{

    CircularDoubleLinkedList circularDoubleLinkedList;
    int count =1;
    /**
     * Creates new form JFThoughts
     */
    public JFThoughts() {
        initComponents();
        circularDoubleLinkedList = new CircularDoubleLinkedList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAThoughts = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jBAddThought = new javax.swing.JButton();
        jBSeeThoughts = new javax.swing.JButton();
        jBRigth = new javax.swing.JButton();
        jBLeft = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTAThoughts.setColumns(20);
        jTAThoughts.setRows(5);
        jScrollPane1.setViewportView(jTAThoughts);

        jLabel1.setText("Thoughts");

        jBAddThought.setText("Add thoughts");
        jBAddThought.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddThoughtActionPerformed(evt);
            }
        });

        jBSeeThoughts.setText("See thoughts");
        jBSeeThoughts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSeeThoughtsActionPerformed(evt);
            }
        });

        jBRigth.setText(">");
        jBRigth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRigthActionPerformed(evt);
            }
        });

        jBLeft.setText("<");
        jBLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLeftActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBSeeThoughts)
                            .addComponent(jBAddThought)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBRigth, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBAddThought)
                .addGap(18, 18, 18)
                .addComponent(jBSeeThoughts)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jBRigth, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jBLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAddThoughtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddThoughtActionPerformed
        JFAddThoughts jFAddThoughts = new JFAddThoughts(circularDoubleLinkedList);
        jFAddThoughts.setVisible(true);
   
    }//GEN-LAST:event_jBAddThoughtActionPerformed

    private void jBSeeThoughtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSeeThoughtsActionPerformed
        if(circularDoubleLinkedList.isEmpty()){
            this.jTAThoughts.setText("Don't have thoughts");
        }else{
        this.jTAThoughts.setText((String) circularDoubleLinkedList.getByPosition(1));
        }
    }//GEN-LAST:event_jBSeeThoughtsActionPerformed

    private void jBLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLeftActionPerformed
         if(count>=0){
             System.out.println(""+count);
            this.jTAThoughts.setText((String)circularDoubleLinkedList.getByPosition(--this.count));
                if(this.count == 0){
                    this.count = circularDoubleLinkedList.getSize()+1;
                    System.out.println(""+circularDoubleLinkedList.getSize());
                }
            }
    }//GEN-LAST:event_jBLeftActionPerformed

    private void jBRigthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRigthActionPerformed
        if(count<=circularDoubleLinkedList.getSize()){
               this.jTAThoughts.setText((String) circularDoubleLinkedList.getByPosition(++this.count));
               if(this.count == circularDoubleLinkedList.getSize()+1){
                    this.count = 0;
                }
        }
    }//GEN-LAST:event_jBRigthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddThought;
    private javax.swing.JButton jBLeft;
    private javax.swing.JButton jBRigth;
    private javax.swing.JButton jBSeeThoughts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAThoughts;
    // End of variables declaration//GEN-END:variables
}
